export const categoriesWidgetsHome = {
  32: "Get Started",
  33: "Business Product Features",
  35: "Try Curriki studio",
  36: "Example Courses",
  75: "Requested Info (provider)",
  58: "About the Program(Providers)",
  59: "learning providers(providers)",
  60: "Certification Process(providers)",
  61: "GETTING INVLOVED (suport learning)",
  62: "Learning Banner(suport learning)",
  63: "ROADMAP (suport learning)",
  64: "LEARN (suport learning)",
  66: "Curriki API(interactive learning)",
  67: "curiki tech(interactive)",
  68: "Get started now(interacive learning)",
  74: "donation (ourmission)",
  71: "Birdies Education (ourmission)",
  72: "Curriki suporters (ourmission)",
  73: "Frequently Questions (ourmission)",
};
